### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActiveEditor is not a function

### ISSUE THREAD

**Issue by brianstanley** [Sass-Director/Sass-Director_Atom#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Ubuntu 14.04.3
**Thrown From**: [sass-director](https://github.com/Sass-Director/Sass-Director_Atom) package, v0.3.0
### Stack Trace

Uncaught TypeError: atom.workspace.getActiveEditor is not a function

```
At /home/brian/.atom/packages/sass-director/lib/sass-director.coffee:27

TypeError: atom.workspace.getActiveEditor is not a function
    at Object.module.exports.__getManifest__ (/home/brian/.atom/packages/sass-director/lib/sass-director.coffee:27:35)
    at Object.module.exports.addManifestFile (/home/brian/.atom/packages/sass-director/lib/sass-director.coffee:16:40)
    at atom-workspace.<anonymous> (/home/brian/.atom/packages/sass-director/lib/sass-director.coffee:9:84)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  3x -5:42.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -3:30.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:35.9.0 command-palette:toggle (atom-pane.pane.active)
     -1:25.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:25.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:18.6.0 application:open-folder (summary.welcome-summary.icon.icon-code)
  2x -0:35.2.0 command-palette:toggle (atom-pane.pane.active)
     -0:23.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.3.0 sass-director:toggle (atom-pane.pane.active)
     -0:14.8.0 application:new-window (atom-pane.pane.active)
     -0:10.4.0 application:open-folder (atom-pane.pane.active)
     -0:09.0 command-palette:toggle (atom-pane.pane.active)
  3x -0:01.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 sass-director:add-manifest-file (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
sass-director, v0.3.0

# Dev
No dev packages
```

**Comment by glrodasz** [comment]
This is happening to me too.
Atom Version 1.5.3
